### PR TITLE
Feature/browser authentication refresh

### PR DESCRIPTION
**Pull request by JakeTheCorn**
#68

### CODE REVIEW

**Comment by BWortman** [comment]
Hi @JakeTheCorn - This looks an awful lot like PR #72. Are they duplicates? (I just quickly skimmed, so there may be some difference...)

**Comment by BWortman** [comment]
@JakeTheCorn - now that PR #72 is merged, is this still relevant?

**Comment by JakeTheCorn** [comment]
@BWortman 

nah, this pr is no longer relevant. 

I'm still looking at the react stuff, but I'll swap in a bit and push up the changes for the webpack build

thanks

**Comment by BWortman** [comment]
Closing. No longer relevant.

**Pull request closed without merging**
