### PR TITLE
Add the ability to switch the api url from commandline

### LINKED ISSUE #11: Default API URL should be overrideable with command line arguments
This is so you can point the UI to the API of your own choosing.

### PR DESCRIPTION
**Pull request by rclanan**
Closes #11

### CODE REVIEW

**Comment by BWortman** [comment]
Great to see progress, but it's not working correctly for me :-(

**Comment by rclanan** [comment]
What? I don't understand what you are saying here. The UI port shouldn't have changed and shouldn't change and can if you set the correct env variable, which is not related to this PR at all. What all steps did you do? It should just be a single argument added to the commandline, no changing of any ports.

**Comment by BWortman** [comment]
Steps to reproduce:
* pull branch
* get clean -dxf
* npm install
* npm test
* npm run dev

Result:
image

If I switch to development branch and run the same steps, this is the result:
image

**Comment by rclanan** [comment]
npm run dev <-- That is not what the readme says to do if you want to change the api url that you are pointing to. 

From the readme: 
 To override the default API url to target a different backend use `--apiurl`:
 ```
 npm run dev -- --apiurl http://dev.local:3001/api/
```

http://dev.local:3001/api/ has to be a valid working api or else you will get a 404 and it won't work, because it's not a valid api. Why would you be switching to an invalid api anyways? 

To test that this PR works properly.. 

* change the port or set the PORT environment variable on the API project
* run the API project so that it's running on the new port
* pull this branch
* git clean -dxf
* npm install
* npm test
* npm run dev -- --apiurl http://127.0.01:<new port here>/api/

**Comment by rclanan** [comment]
Also, how did you get falselogs and falselocations to even show up in there? What is that and where did it come from? You had to have changed something else because that isn't even in the code base.

**Comment by BWortman** [comment]
I have no idea on the faleslogs :-|

In the readme, it says, "To override the default API url to target a different backend use `--apiurl`". But I don't want to override the default. I just wanted to use the default, but I got the results shown above. Here's the corresponding full screen:

image

All is good if I switch back to development branch. Not sure why. Do you want me to try debugging it?

**Comment by BWortman** [comment]
Here's the problem:

image

**Comment by rclanan** [comment]
I found the issue.. just submitted the fix.

You will need to change the API to this or something else to have a valid API running if you want to test the actual changing of the api url. Should run both ways now. 
image

**Comment by BWortman** [comment]
The default works now!

But I'm having problems with a custom url. I have the api running here:

http://127.0.0.1:5000/api

But I get an error when I run this:  npm run dev --apiurl http://127.0.0.1:5000/api/

Here's the error:

ERROR in multi main
Module not found: Error: Cannot resolve module 'http://127.0.0.1:5000/api' in C:\aur\ui
 @ multi main

ERROR in (webpack)-dev-server/client?http://127.0.0.1:8080
Module not found: Error: Cannot resolve module 'sockjs-client' in C:\aur\ui\node_modules\webpack-dev-server\client
 @ (webpack)-dev-server/client?http://127.0.0.1:8080 2:13-37

**Pull request merged**
