### PR TITLE
Break out fleet module into organized folder structure

### LINKED ISSUE #8: Break out fleet module into organized folder structure
The current fleet folder is a mess. It's too flat, containing too many files all in the root. (This is for historical reasons, when we had the .sh-based copy and concat. It was never intended to be the permanent arrangement.) 

Suggested restructure as follows (see screenshot.jpg): 
/fleet - contains root items (fleet.header.html, fleet.js, fleet.module.js) 
/fleet/locations - contains location-related files (fleet-locations.controller.js, fleet-locations.html, fleet-locations-id-column.html, etc.) 
/fleet/locations/detail - contains the location detail-related files marked with blue 
/fleet/vehicles - contains the vehicle-related files marked with green 
/fleet/vehicles/detail - contains the vehicle detail-related files marked with orange 
/fleet/reports - contains reports-related files

image

### PR DESCRIPTION
**Pull request by rclanan**
Closes #8

### CODE REVIEW

**Comment by rclanan** [comment]
This PR will also close #25

**Comment by BWortman** [comment]
The top 4 indicated files should be moved to the detail folder. The fleet-locations.html file should be moved to the locations folder.
image

**Comment by BWortman** [comment]
The top 4 indicated files need to be moved to the detail folder.

image

**Comment by rclanan** [comment]
Should be corrected now.

**Pull request merged**
